services:
  cryptopro-php:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - CONTAINER_REGISTRY
        - DEBIAN_VERSION

        - PHP_VERSION_MAJOR
        - PHP_VERSION_MINOR
        - PHP_VERSION_PATCH

        - CSP_VERSION_MAIN
        - CSP_VERSION_REDACTION

        - COMPOSER_VERSION
        - XDEBUG_VERSION

        - CI_ENVIRONMENT_NAME

        - CRYPTOPRO_LICENSE
        - CRYPTOPRO_CERTIFICATE_PFX_FILE_NAME
        - CRYPTOPRO_CERTIFICATE_PFX_FILE_PIN_OLD
        - CRYPTOPRO_CERTIFICATE_PFX_FILE_PIN_NEW
    image: cryptopro-php:latest
    container_name: cryptopro-php
    environment:
      - XDEBUG_IP
      - XDEBUG_IS_LOGS_VISIBLE
      - PHP_IDE_CONFIG

      - TZ

      - CRYPTOPRO_CERTIFICATE_PFX_FILE_HASH
    volumes:
      - ./certificates:/app/certificates
      - ./data:/app/data
      - ./src:/app/src
      - ./entrypoint.sh:/app/entrypoint.sh