services:
  cryptopro-php:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - CONTAINER_REGISTRY
        - DEBIAN_VERSION

        - PHP_VERSION_MAJOR
        - PHP_VERSION_MINOR
        - PHP_VERSION_PATCH

        - CSP_VERSION_MAIN
        - CSP_VERSION_REDACTION

        - COMPOSER_VERSION
        - XDEBUG_VERSION

        - CI_ENVIRONMENT_NAME
    image: cryptopro-php:latest
    container_name: cryptopro-php
    environment:
      - XDEBUG_IP
      - XDEBUG_IS_LOGS_VISIBLE
      - PHP_IDE_CONFIG

      - TZ